/*
 * This source file was generated by the Gradle 'init' task
 */
package org.timetorunserver;

import org.timetorunserver.space.Graph;

import java.nio.file.Path;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {
        if(args.length != 3) {
            return;
        }
        Path mapFile = Paths.get(args[0]);
        Graph graph = new Graph();
        if(!graph.getGraphFromFile(mapFile)) {
            graph.draw();
        }


        while (true){
            break;
        }
    }
}
